apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: whisper-asr
  labels:
    app: whisper-asr
    app.kubernetes.io/name: whisper-asr
    app.kubernetes.io/component: transcription
    app.kubernetes.io/part-of: griot-and-grits
spec:
  to:
    kind: Service
    name: whisper-asr
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
