apiVersion: batch/v1
kind: Job
metadata:
  name: init-mongodb
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: mongo:7.0.14
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Waiting for MongoDB to be ready..."
          until mongosh "mongodb://admin:gngdevpass12@mongodb:27017/gngdb?authSource=admin" --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
            echo "MongoDB is unavailable - sleeping"
            sleep 2
          done

          echo "MongoDB is ready - creating collections and sample data..."

          mongosh "mongodb://admin:gngdevpass12@mongodb:27017/gngdb?authSource=admin" <<EOF
            // Create collections collection with sample data
            db.collections.insertOne({
              name: "Demo Collection",
              description: "Sample collection for hackathon",
              created_at: new Date(),
              owner: "admin_demo"
            });

            // Create artifacts collection
            db.artifacts.insertOne({
              title: "Sample Artifact",
              collection_id: "demo",
              created_at: new Date(),
              metadata: {
                type: "demo",
                status: "active"
              }
            });

            print("✓ Sample data created successfully");
          EOF

          echo "Done."
