apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: image-registry.openshift-image-registry.svc:5000/openshift/mongodb:latest
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "gngdevpass12"
        - name: MONGO_INITDB_DATABASE
          value: "gngdb"
        resources:
          requests:
            memory: "256Mi"   # Increased from 128Mi
            cpu: "50m"
          limits:
            memory: "1Gi"   # Increased from 256Mi to prevent OOMKill
            cpu: "500m"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        emptyDir: {}