apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.access.redhat.com/ubi9/nodejs-20:latest
        workingDir: /tmp
        command: ["/bin/bash", "-c"]
        args:
        - |
          git clone https://github.com/griot-and-grits/gng-web.git /tmp/app
          cd /tmp/app

          npm install

          # Disable turbopack for faster compilation in containers
          sed -i 's/"dev": "next dev --turbopack"/"dev": "next dev"/g' package.json

          npm run dev -- --hostname 0.0.0.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://backend-NAMESPACE.CLUSTER_DOMAIN"
        - name: NEXTAUTH_URL
          value: "https://frontend-NAMESPACE.CLUSTER_DOMAIN"
        - name: NEXT_PUBLIC_BASE_URL
          value: "https://frontend-NAMESPACE.CLUSTER_DOMAIN"
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
