apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.access.redhat.com/ubi9/nodejs-20:latest
        workingDir: /tmp
        command: ["/bin/bash", "-c"]
        args:
        - |
          git clone https://github.com/griot-and-grits/gng-web.git /tmp/app
          cd /tmp/app
          npm install
          npm run dev -- --host 0.0.0.0
        ports:
        - containerPort: 5173
          name: http
        env:
        - name: VITE_API_URL
          value: "https://backend-NAMESPACE.CLUSTER_DOMAIN"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
